Repository gunrock/essentials, pull requests merged in 2021-04, with the labels that each got.

#40 Implementing PageRank
  CMakeLists.txt
  examples/CMakeLists.txt
  examples/pr/CMakeLists.txt
  examples/pr/pr.cu
  include/gunrock/applications/pr.hxx
Labels: 🍍 algorithms, 🐙 c++

#48 Documentations and more...
  CMakeLists.txt
  LICENSE
  README.md
  doxygen/essentials.doxygen
  examples/CMakeLists.txt
  examples/pr/CMakeLists.txt
  examples/pr/pr.cu
  include/gunrock/algorithms/sort/radix_sort.hxx
  include/gunrock/applications/bfs.hxx
  include/gunrock/applications/color.hxx
  include/gunrock/applications/geo.hxx
  include/gunrock/applications/pr.hxx
  include/gunrock/applications/sssp.hxx
  include/gunrock/cuda/context.hxx
  include/gunrock/framework/enactor.hxx
  include/gunrock/framework/frontier/frontier.hxx
  include/gunrock/framework/frontier/vector_frontier.hxx
  include/gunrock/framework/operators/advance/advance.hxx
  include/gunrock/framework/operators/advance/all_edges.hxx
  include/gunrock/framework/operators/configs.hxx
  include/gunrock/framework/operators/filter/filter.hxx
  include/gunrock/framework/operators/filter/uniquify.hxx
  include/gunrock/framework/operators/for/for.hxx
  include/gunrock/framework/operators/for/for_each.hxx
  include/gunrock/framework/operators/operators.hxx
  include/gunrock/framework/operators/uniquify/unique.hxx
  include/gunrock/framework/operators/uniquify/unique_copy.hxx
  include/gunrock/framework/operators/uniquify/uniquify.hxx
  include/gunrock/framework/problem.hxx
Labels: 🍍 algorithms, 🐛 bug, 📋 documentation, 🚂 operators

#57 Bug-fixes, minor enhancements and clean-up with unit tests.
  CMakeLists.txt
  LICENSE
  datasets/toy.mtx
  examples/CMakeLists.txt
  include/gunrock/framework/enactor.hxx
  include/gunrock/graph/csr.hxx
  unittests/CMakeLists.txt
  unittests/Makefile.inc
  unittests/array/CMakeLists.txt
  unittests/array/Makefile
  unittests/contexts/Makefile
  unittests/coo_to_csr/Makefile
  unittests/coo_to_csr/test.mtx
  unittests/csr/Makefile
  unittests/device_properties/Makefile
  unittests/experiments/Makefile
  unittests/for/Makefile
  unittests/formats/Makefile
  unittests/graph/Makefile
  unittests/graph_load/Makefile
  unittests/graph_load/test.mtx
  unittests/launch_box/Makefile
  unittests/matrix_market/Makefile
  unittests/matrix_market/test.mtx
  unittests/memory/Makefile
  unittests/mtx2bin/CMakeLists.txt
  unittests/mtx2bin/mtx2bin.cu
  unittests/mtx2bin/test.mtx
  unittests/problem/Makefile
  unittests/shared_ptr/Makefile
  unittests/src_vertex_test/CMakeLists.txt
  unittests/src_vertex_test/src_vertex_test.cu
  unittests/src_vertex_test/test.mtx
  unittests/type_limits/Makefile
Labels: 🏭 build, 🐛 bug

#63 [BUGFIX] Order of values passed to `csc.set`
  include/gunrock/graph/csc.hxx
Labels: 🏡 api, 🐛 bug

#60 [APP] Betweenness Centrality (V3)
  examples/CMakeLists.txt
  examples/bc/CMakeLists.txt
  examples/bc/bc.cu
  include/gunrock/applications/bc.hxx
Labels: 🍍 algorithms, 🏡 api
